import type { Metadata } from "next";
import localFont from 'next/font/local'
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

const roboto = localFont({
  src: [
    {
      path: './Roboto-Thin.woff2',
      weight: '100',
    },
    {
      path: './Roboto-Light.woff2',
      weight: '300',
    },
    {
      path: './Roboto-Regular.woff2',
      weight: '400',
    },
    {
      path: './Roboto-Medium.woff2',
      weight: '500',
    },
    {
      path: './Roboto-Bold.woff2',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStorage = cookies()
  const sessionToken = cookieStorage.get('sessionToken')

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider initialSessionToken={sessionToken?.value}>
            {children}
          </AppProvider>
        </ThemeProvider>
        <Toaster/>
        </body>
    </html>
  );
}
